import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { FileText, Calendar } from "lucide-react";

const TermsOfServicePage = () => {
  const lastUpdated = "January 15, 2026";

  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: `By accessing or using ShadowTalk AI ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, you may not access the Service.

These Terms apply to all visitors, users, and others who access or use the Service. By using the Service, you represent that you are at least 13 years of age, or the age of majority in your jurisdiction, whichever is greater.`
    },
    {
      title: "2. Description of Service",
      content: `ShadowTalk AI provides an AI-powered assistant platform that includes:

• Chat-based AI assistance with multiple model options
• Offline AI capabilities using local models
• Code generation, translation, and creative writing features
• API access for developers (on applicable plans)
• Collaborative features and workspace management

We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time without prior notice.`
    },
    {
      title: "3. User Accounts",
      content: `To access certain features of the Service, you must create an account. You agree to:

• Provide accurate, current, and complete information
• Maintain the security of your password and account
• Accept responsibility for all activities under your account
• Notify us immediately of any unauthorized use

We reserve the right to terminate accounts that violate these Terms or engage in fraudulent activity.`
    },
    {
      title: "4. Acceptable Use",
      content: `You agree not to use the Service to:

• Violate any laws or regulations
• Infringe on intellectual property rights
• Generate harmful, abusive, or illegal content
• Attempt to bypass security measures or access restrictions
• Interfere with the proper functioning of the Service
• Use automated systems to access the Service without permission
• Engage in any activity that could damage our reputation

We reserve the right to investigate and take appropriate action against violations, including account termination.`
    },
    {
      title: "5. Intellectual Property",
      content: `**Our Content**: The Service and its original content, features, and functionality are owned by ShadowTalk AI and are protected by international copyright, trademark, and other intellectual property laws.

**Your Content**: You retain ownership of content you create using the Service. By using the Service, you grant us a limited license to process your content solely for the purpose of providing the Service.

**AI-Generated Content**: Content generated by the AI is provided "as is." You are responsible for reviewing and using AI-generated content appropriately.`
    },
    {
      title: "6. Subscription and Payments",
      content: `**Free Tier**: We offer a free tier with limited features and usage.

**Paid Plans**: Premium features require a paid subscription. By subscribing, you agree to:
• Pay all fees according to the pricing plan you selected
• Authorize automatic renewal unless you cancel before the renewal date
• Accept that fees are non-refundable except as required by law or our refund policy

**Refunds**: We offer a 14-day money-back guarantee for new subscriptions. Contact support for refund requests.`
    },
    {
      title: "7. Limitation of Liability",
      content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW:

• The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind
• We do not guarantee the accuracy, completeness, or usefulness of AI-generated content
• We are not liable for any indirect, incidental, special, consequential, or punitive damages
• Our total liability shall not exceed the amount you paid us in the twelve months prior to the claim

You acknowledge that AI systems may produce inaccurate or inappropriate responses, and you are responsible for verifying any important information.`
    },
    {
      title: "8. Indemnification",
      content: `You agree to defend, indemnify, and hold harmless ShadowTalk AI and its officers, directors, employees, and agents from any claims, damages, obligations, losses, liabilities, costs, or expenses arising from:

• Your use of the Service
• Your violation of these Terms
• Your violation of any third-party rights
• Any content you submit or generate using the Service`
    },
    {
      title: "9. Termination",
      content: `We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including:

• Breach of these Terms
• Request by law enforcement or government agencies
• Extended periods of inactivity
• Unexpected technical or security issues

Upon termination, your right to use the Service will immediately cease. You may export your data before termination using our export features.`
    },
    {
      title: "10. Governing Law",
      content: `These Terms shall be governed by and construed in accordance with the laws of Pakistan, without regard to its conflict of law provisions.

Any disputes arising from these Terms or the Service shall be resolved through binding arbitration in Karachi, Pakistan, unless prohibited by local law.`
    },
    {
      title: "11. Changes to Terms",
      content: `We reserve the right to modify these Terms at any time. We will notify you of any changes by:

• Posting the new Terms on this page
• Updating the "Last Updated" date
• Sending you an email notification for material changes

Your continued use of the Service after changes become effective constitutes acceptance of the revised Terms.`
    },
    {
      title: "12. Contact Us",
      content: `If you have questions about these Terms of Service, please contact us at:

**Email**: legal@shadowtalk.ai
**Address**: Karachi, Pakistan`
    }
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      
      {/* Hero Section */}
      <section className="pt-24 pb-16 px-4">
        <div className="container mx-auto max-w-4xl text-center">
          <Badge variant="secondary" className="mb-4">
            <FileText className="h-3 w-3 mr-1" />
            Legal
          </Badge>
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Terms of <span className="gradient-text">Service</span>
          </h1>
          <div className="flex items-center justify-center gap-2 text-muted-foreground">
            <Calendar className="h-4 w-4" />
            <span>Last updated: {lastUpdated}</span>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-8 px-4">
        <div className="container mx-auto max-w-4xl">
          <Card className="mb-8">
            <CardContent className="p-6">
              <p className="text-muted-foreground leading-relaxed">
                Welcome to ShadowTalk AI. These Terms of Service ("Terms") govern your access to and use of 
                our website, products, and services. Please read these Terms carefully before using our Service.
              </p>
            </CardContent>
          </Card>

          <div className="space-y-8">
            {sections.map((section, index) => (
              <div key={index}>
                <h2 className="text-xl font-bold mb-4">{section.title}</h2>
                <div className="text-muted-foreground leading-relaxed whitespace-pre-line">
                  {section.content}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsOfServicePage;
